#!/bin/sh
set -e
getent group pryecip-connector >/dev/null || addgroup --system pryecip-connector
getent passwd pryecip-connector >/dev/null || adduser --system --ingroup pryecip-connector --home /var/lib/pryecip-local-connector --no-create-home pryecip-connector
install -d -o pryecip-connector -g pryecip-connector -m 0750 /var/lib/pryecip-local-connector
install -d -o root -g pryecip-connector -m 0750 /etc/pryecip-local-connector
#DEBHELPER#
