import { useRef, useState, type FormEvent } from 'react';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { NavLink } from 'react-router-dom';
import { ApiError, staffApi } from '../api/client';
import type { InventoryIntelligence, InventoryValuationSnapshot } from '../api/contracts';
import { useStaffContext } from '../context/StaffContext';
import { useAuth } from '../session/AuthContext';

const failure=(value:unknown)=>value instanceof ApiError&&value.status===409?'El estado cambió en otra sesión. Actualiza antes de reintentar.':value instanceof Error?value.message:'No fue posible completar la operación.';
const itemName=(data:InventoryIntelligence,id:number)=>data.stock.find((row)=>row.inventory_item_id===id)?.name??`Artículo #${id}`;
const day=(value:string|null)=>value?new Date(`${value}T00:00:00`).toLocaleDateString('es-MX'):'Sin evidencia';

export function Replenishment({data}:{data:InventoryIntelligence}) {
  const {location}=useStaffContext(); const {hasPermission}=useAuth(); const cache=useQueryClient();
  const policies=useQuery({queryKey:['inventory','replenishment',location?.id],queryFn:()=>staffApi.replenishmentPolicies(location!.id),enabled:Boolean(location&&hasPermission('inventory.replenishment.read')),retry:false});
  const [itemId,setItemId]=useState(0); const [minimum,setMinimum]=useState(''); const [target,setTarget]=useState('');
  const existing=policies.data?.items.find((row)=>row.inventory_item_id===itemId&&row.warehouse_id===data.warehouses[0]?.id);
  const save=useMutation({mutationFn:()=>staffApi.putReplenishmentPolicy(data.warehouses[0].id,itemId,{expected_version:existing?.version??0,status:'ACTIVE',minimum_quantity:minimum||null,target_quantity:target||null,source_uom:data.stock.find((row)=>row.inventory_item_id===itemId)!.base_uom}),onSuccess:()=>cache.invalidateQueries({queryKey:['inventory','replenishment']})});
  if(!hasPermission('inventory.replenishment.read')) return <section className="inventory-panel"><h2>Reabastecimiento</h2><p className="inventory-denied">Sin permiso para consultar políticas.</p></section>;
  return <div className="inventory-stack"><section className="inventory-panel inventory-form"><div className="inventory-panel-heading"><div><h2>Política humana de reabastecimiento</h2><p>La sugerencia es informativa. Nunca crea, envía ni aprueba una orden automáticamente.</p></div><NavLink className="secondary-button button-link" to="/inventory/purchase-orders">Crear orden de compra</NavLink></div>{hasPermission('inventory.replenishment.manage')?<form className="inventory-form-grid" onSubmit={(event:FormEvent)=>{event.preventDefault();save.mutate();}}><label>Artículo<select required value={itemId} onChange={(event)=>{const id=Number(event.target.value);setItemId(id);const found=policies.data?.items.find((row)=>row.inventory_item_id===id);setMinimum(found?.minimum_quantity??'');setTarget(found?.target_quantity??'');}}><option value="">Seleccionar</option>{data.stock.filter((row,index,rows)=>rows.findIndex((other)=>other.inventory_item_id===row.inventory_item_id)===index).map((row)=><option key={row.inventory_item_id} value={row.inventory_item_id}>{row.name}</option>)}</select></label><label>Mínimo / reorden<input inputMode="decimal" value={minimum} onChange={(event)=>setMinimum(event.target.value)}/></label><label>Objetivo / par<input required inputMode="decimal" value={target} onChange={(event)=>setTarget(event.target.value)}/></label><button className="primary-button" disabled={!itemId||!target||save.isPending}>{save.isPending?'Guardando…':'Guardar política'}</button></form>:null}{save.error?<p role="alert" className="inventory-feedback inventory-feedback--error">{failure(save.error)}</p>:null}</section><section className="inventory-panel"><h2>Revisión de sugerencias</h2>{policies.isPending?<p role="status">Cargando políticas…</p>:null}{policies.error?<p role="alert" className="inventory-feedback inventory-feedback--error">{failure(policies.error)}</p>:null}{!policies.isPending&&!policies.data?.items.length?<p className="inventory-empty">No hay políticas configuradas. Define un objetivo para recibir una sugerencia reproducible.</p>:null}{policies.data?.items.length?<div className="inventory-table-wrap" tabIndex={0} aria-label="Políticas y sugerencias de reabastecimiento"><table className="inventory-table"><thead><tr><th>Artículo</th><th>En existencia</th><th>En orden</th><th>Objetivo</th><th>Cantidad sugerida</th><th>Acción humana</th></tr></thead><tbody>{policies.data.items.map((row)=><tr key={row.id}><td><strong>{itemName(data,row.inventory_item_id)}</strong><small>{row.status} · versión {row.version}</small></td><td>{row.on_hand} {row.source_uom}</td><td>{row.on_order} {row.source_uom}<small>No es stock</small></td><td>{row.target_quantity??'Sin objetivo'} {row.source_uom}</td><td><strong>{row.suggested_quantity} {row.source_uom}</strong><small>max(objetivo − existencia, 0)</small></td><td><NavLink to="/inventory/purchase-orders">Revisar y crear OC</NavLink></td></tr>)}</tbody></table></div>:null}</section></div>;
}

export function Lots({data}:{data:InventoryIntelligence}) {
  const {location}=useStaffContext(); const {hasPermission}=useAuth();
  const lots=useQuery({queryKey:['inventory','lots',location?.id],queryFn:()=>staffApi.inventoryLots(location!.id),enabled:Boolean(location&&hasPermission('inventory.lot.read')),retry:false});
  if(!hasPermission('inventory.lot.read')) return <section className="inventory-panel"><h2>Lotes</h2><p className="inventory-denied">Sin permiso para consultar trazabilidad.</p></section>;
  return <section className="inventory-panel"><div className="inventory-panel-heading"><div><h2>Trazabilidad de lotes</h2><p>El saldo se deriva exclusivamente de movimientos; una fecha vencida sólo genera atención y nunca una baja automática.</p></div></div>{lots.isPending?<p role="status">Cargando lotes…</p>:null}{lots.error?<p role="alert" className="inventory-feedback inventory-feedback--error">{failure(lots.error)}</p>:null}{!lots.isPending&&!lots.data?.items.length?<p className="inventory-empty">No hay lotes recibidos o producidos con evidencia.</p>:null}{lots.data?.items.length?<div className="inventory-table-wrap" tabIndex={0} aria-label="Lotes y trazabilidad; desplázate horizontalmente si es necesario"><table className="inventory-table"><thead><tr><th>Artículo / lote</th><th>Origen</th><th>Saldo derivado</th><th>Fechas</th><th>Estado</th><th>Evidencia de costo</th></tr></thead><tbody>{lots.data.items.map((row)=><tr key={row.id}><td><strong>{itemName(data,row.inventory_item_id)}</strong><small>{row.lot_code}</small></td><td>{row.origin_type==='GOODS_RECEIPT'?'Recepción':'Preparación'}<small>{new Date(row.origin_at).toLocaleString('es-MX')}</small></td><td>{row.balance} {row.base_uom_evidence}<small>Original {row.original_quantity}</small></td><td><small>Fabricación: {day(row.manufacture_date)}</small><small>Caducidad: {day(row.expiry_date)}</small><small>Consumo preferente: {day(row.best_before_date)}</small></td><td><span className="inventory-badge">{row.date_state??'SIN FECHA'}</span><small>{row.date_state==='EXPIRED'?'Requiere revisión; sin baja automática':''}</small></td><td>{row.cost_visible?(row.cost_evidence_status==='RESOLVED'?`${row.unit_cost_evidence} ${row.cost_currency_evidence}`:'NO DERIVABLE'):'Información monetaria protegida.'}</td></tr>)}</tbody></table></div>:null}</section>;
}

export function Valuation({data}:{data:InventoryIntelligence}) {
  const {location}=useStaffContext(); const {hasPermission}=useAuth(); const cache=useQueryClient(); const key=useRef<string | undefined>(undefined);
  const [asOf,setAsOf]=useState(()=>{const now=new Date();now.setMinutes(now.getMinutes()-now.getTimezoneOffset());return now.toISOString().slice(0,16)}); const [currency,setCurrency]=useState('MXN'); const [current,setCurrent]=useState<InventoryValuationSnapshot|null>(null);
  const snapshots=useQuery({queryKey:['inventory','valuations',location?.id],queryFn:()=>staffApi.valuationSnapshots(location!.id),enabled:Boolean(location&&hasPermission('inventory.valuation.read')),retry:false});
  const create=useMutation({mutationFn:()=>{key.current??=crypto.randomUUID();return staffApi.createValuationSnapshot({warehouse_id:data.warehouses[0].id,as_of:new Date(asOf).toISOString(),currency,valuation_method:'STANDARD_COST'},key.current)},onSuccess:(value)=>{setCurrent(value);void cache.invalidateQueries({queryKey:['inventory','valuations']})}});
  if(!hasPermission('inventory.valuation.read')) return <section className="inventory-panel"><h2>Valuación</h2><p className="inventory-denied">Sin permiso para consultar snapshots.</p></section>;
  const selected=current??snapshots.data?.items[0];
  return <div className="inventory-two-columns"><form className="inventory-panel inventory-form" onSubmit={(event)=>{event.preventDefault();key.current=undefined;create.mutate();}}><h2>Snapshot histórico</h2><p className="inventory-state-note"><strong>STANDARD_COST</strong> únicamente. No es FIFO, costo de última compra ni promedio ponderado de inventario.</p><label>Al corte<input type="datetime-local" required value={asOf} onChange={(event)=>setAsOf(event.target.value)}/></label><label>Moneda comparable<input maxLength={3} required value={currency} onChange={(event)=>setCurrency(event.target.value.toUpperCase())}/></label><button className="primary-button" disabled={!hasPermission('inventory.valuation.create')||create.isPending}>{create.isPending?'Finalizando…':'Crear snapshot inmutable'}</button>{create.error?<p role="alert" className="inventory-feedback inventory-feedback--error">{failure(create.error)}</p>:null}</form><section className="inventory-panel"><h2>Evidencia finalizada</h2>{snapshots.isPending?<p role="status">Cargando snapshots…</p>:null}{snapshots.error?<p role="alert" className="inventory-feedback inventory-feedback--error">{failure(snapshots.error)}</p>:null}{!selected?<p className="inventory-empty">No hay snapshots finalizados.</p>:<><p className="inventory-lifecycle">FINALIZED · STANDARD_COST</p><dl className="inventory-evidence"><div><dt>Al corte</dt><dd>{new Date(selected.as_of).toLocaleString('es-MX')}</dd></div><div><dt>Cursor</dt><dd>#{selected.movement_cursor}</dd></div><div><dt>Total derivable</dt><dd>{selected.cost_visible?`${selected.derivable_total_value} ${selected.currency}`:'Protegido por permisos'}</dd></div><div><dt>No derivables</dt><dd>{selected.non_derivable_line_count}</dd></div></dl><div className="inventory-table-wrap" tabIndex={0} aria-label="Líneas del snapshot histórico"><table className="inventory-table"><thead><tr><th>Artículo</th><th>Cantidad al corte</th><th>Estado</th><th>Costo estándar</th><th>Valor</th></tr></thead><tbody>{selected.lines.map((row)=><tr key={row.id}><td>{itemName(data,row.inventory_item_id)}</td><td>{row.quantity_as_of}</td><td>{row.evidence_status}</td><td>{selected.cost_visible?(row.unit_cost_evidence==null?'NO DERIVABLE':`${row.unit_cost_evidence} ${row.cost_currency_evidence}`):'PROTEGIDO'}</td><td>{selected.cost_visible?(row.line_value??'NO DERIVABLE'):'PROTEGIDO'}</td></tr>)}</tbody></table></div><p className="inventory-privacy">Finalizado e inmutable: movimientos o revisiones de costo posteriores no cambian esta evidencia.</p></>}</section></div>;
}
