import { useRef, useState, type FormEvent } from 'react';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';

import { ApiError, staffApi } from '../api/client';
import type { InventoryIntelligence, PreparationBatch } from '../api/contracts';
import { useStaffContext } from '../context/StaffContext';
import { useAuth } from '../session/AuthContext';

interface ComponentDraft { inventory_item_id:number; expected_quantity:string; source_uom:string; yield_basis:boolean }

function errorMessage(error:unknown) { return error instanceof ApiError ? error.message : error instanceof Error ? error.message : 'No fue posible completar la operación.'; }
function itemName(items:Array<{id:number;name:string}>,id:number) { return items.find((row)=>row.id===id)?.name ?? `Artículo #${id}`; }

export function Preparations({data}:{data:InventoryIntelligence}) {
  const {location}=useStaffContext(); const {hasPermission}=useAuth(); const queryClient=useQueryClient(); const keys=useRef(new Map<number,string>());
  const canManage=hasPermission('inventory.preparation.manage');
  const [outputItemId,setOutputItemId]=useState(0); const [expectedOutput,setExpectedOutput]=useState(''); const [componentItemId,setComponentItemId]=useState(0); const [componentQuantity,setComponentQuantity]=useState(''); const [yieldBasis,setYieldBasis]=useState(false); const [components,setComponents]=useState<ComponentDraft[]>([]);
  const [recipeId,setRecipeId]=useState(0); const [actualInputs,setActualInputs]=useState<Record<number,string>>({}); const [actualOutput,setActualOutput]=useState(''); const [reference,setReference]=useState(''); const [current,setCurrent]=useState<PreparationBatch|null>(null); const [compositionError,setCompositionError]=useState<string>();
  const items=useQuery({queryKey:['inventory','items',location?.id],queryFn:()=>staffApi.inventoryItems(location!.id),enabled:Boolean(location&&hasPermission('inventory.preparation.read')),retry:false});
  const recipes=useQuery({queryKey:['inventory','preparation-recipes',location?.id],queryFn:()=>staffApi.preparationRecipes(location!.id),enabled:Boolean(location&&hasPermission('inventory.preparation.read')),retry:false});
  const batches=useQuery({queryKey:['inventory','preparation-batches',location?.id],queryFn:()=>staffApi.preparationBatches(location!.id),enabled:Boolean(location&&hasPermission('inventory.preparation.read')),retry:false});
  const selectedRecipe=recipes.data?.items.find((row)=>row.id===recipeId); const itemRows=items.data?.items ?? [];
  const publish=useMutation({mutationFn:()=>staffApi.publishPreparationRecipe({location_id:location!.id,output_inventory_item_id:outputItemId,expected_output_quantity:expectedOutput,output_uom:itemRows.find((row)=>row.id===outputItemId)!.base_uom,status:'ACTIVE',expected_revision:Math.max(0,...(recipes.data?.items.filter((row)=>row.output_inventory_item_id===outputItemId).map((row)=>row.revision)??[])),components}),onSuccess:()=>{setComponents([]);setOutputItemId(0);setExpectedOutput('');void queryClient.invalidateQueries({queryKey:['inventory','preparation-recipes']});}});
  const create=useMutation({mutationFn:()=>staffApi.createPreparationBatch({recipe_version_id:recipeId,warehouse_id:data.warehouses[0].id,reference:reference||null,inputs:selectedRecipe!.components.map((row)=>({recipe_component_id:row.id,source_quantity:actualInputs[row.id],source_uom:row.source_uom})),output_quantity:actualOutput,output_uom:selectedRecipe!.output_source_uom}),onSuccess:(value)=>{setCurrent(value);void queryClient.invalidateQueries({queryKey:['inventory','preparation-batches']});}});
  const action=useMutation({mutationFn:(name:'start'|'complete'|'cancel')=>{let key:string|undefined;if(name==='complete'){key=keys.current.get(current!.id);if(!key){key=crypto.randomUUID();keys.current.set(current!.id,key);}}return staffApi.actOnPreparationBatch(current!.id,name,current!.version,key);},onSuccess:(value)=>{setCurrent(value);void queryClient.invalidateQueries({queryKey:['inventory']});}});
  const addComponent=()=>{const item=itemRows.find((row)=>row.id===componentItemId);if(!item||!componentQuantity)return;if(componentItemId===outputItemId||components.some((row)=>row.inventory_item_id===componentItemId)){setCompositionError('Cada entrada debe ser única y distinta de la salida.');return;}setComponents((rows)=>[...rows.map((row)=>yieldBasis?{...row,yield_basis:false}:row),{inventory_item_id:item.id,expected_quantity:componentQuantity,source_uom:item.base_uom,yield_basis:yieldBasis}]);setComponentItemId(0);setComponentQuantity('');setYieldBasis(false);setCompositionError(undefined);};
  const submitRecipe=(event:FormEvent)=>{event.preventDefault();if(!components.length||components.filter((row)=>row.yield_basis).length!==1){setCompositionError('Agrega entradas y marca exactamente una como base del rendimiento.');return;}publish.mutate();};
  const chooseRecipe=(id:number)=>{setRecipeId(id);const selected=recipes.data?.items.find((row)=>row.id===id);setActualInputs(Object.fromEntries(selected?.components.map((row)=>[row.id,row.expected_quantity])??[]));setActualOutput(selected?.expected_output_quantity??'');setCurrent(null);};
  if(!hasPermission('inventory.preparation.read')) return <section className="inventory-panel"><h2>Preparaciones</h2><p className="inventory-denied">Sin permiso para consultar preparaciones.</p></section>;
  const error=publish.error||create.error||action.error||items.error||recipes.error||batches.error;
  return <div className="inventory-two-columns">
    {canManage?<form className="inventory-panel inventory-form" onSubmit={submitRecipe}><div className="inventory-panel-heading"><div><h2>Nueva versión de preparación</h2><p className="inventory-state-note">Una versión publicada es inmutable. El rendimiento normal no crea una pérdida.</p></div></div>
      <label>Artículo preparado<select required value={outputItemId} onChange={(event)=>{setOutputItemId(Number(event.target.value));setComponents([]);}}><option value="">Seleccionar</option>{itemRows.filter((row)=>row.status==='ACTIVE').map((row)=><option key={row.id} value={row.id}>{row.name} · {row.base_uom}</option>)}</select></label>
      <label>Salida esperada<input required inputMode="decimal" value={expectedOutput} onChange={(event)=>setExpectedOutput(event.target.value)}/></label>
      <fieldset className="inventory-line-composer"><legend>Entrada esperada</legend><label>Artículo de entrada<select value={componentItemId} onChange={(event)=>setComponentItemId(Number(event.target.value))}><option value="">Seleccionar</option>{itemRows.filter((row)=>row.id!==outputItemId&&row.status==='ACTIVE').map((row)=><option key={row.id} value={row.id}>{row.name} · {row.base_uom}</option>)}</select></label><label>Cantidad esperada<input inputMode="decimal" value={componentQuantity} onChange={(event)=>setComponentQuantity(event.target.value)}/></label><label className="inventory-inline-check"><input type="checkbox" checked={yieldBasis} onChange={(event)=>setYieldBasis(event.target.checked)}/> Base del rendimiento</label><button type="button" className="secondary-button" onClick={addComponent}>Agregar entrada</button></fieldset>
      {components.length?<ol className="inventory-draft-lines">{components.map((row,index)=><li key={row.inventory_item_id}><span><strong>{itemName(itemRows,row.inventory_item_id)}</strong><small>{row.expected_quantity} {row.source_uom}{row.yield_basis?' · base del rendimiento':''}</small></span><button type="button" className="secondary-button" onClick={()=>setComponents((values)=>values.filter((_,i)=>i!==index))}>Quitar entrada {index+1}</button></li>)}</ol>:<p className="inventory-empty">Define múltiples entradas y una sola salida primaria.</p>}
      {compositionError?<p className="inventory-feedback inventory-feedback--error" role="alert">{compositionError}</p>:null}<button className="primary-button" disabled={!outputItemId||!expectedOutput||!components.length||publish.isPending}>{publish.isPending?'Publicando…':'Publicar versión inmutable'}</button>
    </form>:null}
    <section className="inventory-panel" aria-labelledby="preparation-batch-heading"><div className="inventory-panel-heading"><div><h2 id="preparation-batch-heading">Lote y rendimiento real</h2><p>Las existencias cambian atómicamente sólo al completar.</p></div></div>
      <label>Receta publicada<select value={recipeId} onChange={(event)=>chooseRecipe(Number(event.target.value))}><option value="">Seleccionar</option>{recipes.data?.items.filter((row)=>row.status==='ACTIVE').map((row)=><option key={row.id} value={row.id}>{itemName(itemRows,row.output_inventory_item_id)} · revisión {row.revision}</option>)}</select></label>
      {!recipes.isPending&&!recipes.data?.items.length?<p className="inventory-empty">No hay receta activa. Publica una versión para comenzar.</p>:null}
      {selectedRecipe&&!current&&canManage?<div className="inventory-form"><p className="inventory-state-note">Esperado: {selectedRecipe.expected_output_quantity} {selectedRecipe.output_source_uom} · rendimiento {selectedRecipe.expected_yield}</p>{selectedRecipe.components.map((row)=><label key={row.id}>Entrada real · {itemName(itemRows,row.inventory_item_id)}<input aria-label={`Entrada real ${itemName(itemRows,row.inventory_item_id)}`} inputMode="decimal" value={actualInputs[row.id]??''} onChange={(event)=>setActualInputs((values)=>({...values,[row.id]:event.target.value}))}/></label>)}<label>Salida real<input inputMode="decimal" value={actualOutput} onChange={(event)=>setActualOutput(event.target.value)}/></label><label>Referencia<input maxLength={200} value={reference} onChange={(event)=>setReference(event.target.value)}/></label><button className="primary-button" disabled={create.isPending||!actualOutput||selectedRecipe.components.some((row)=>!actualInputs[row.id])} onClick={()=>create.mutate()}>{create.isPending?'Creando…':'Crear lote DRAFT'}</button></div>:null}
      {selectedRecipe&&!current&&!canManage?<p className="inventory-state-note">Consulta disponible; la creación de lotes requiere permiso de gestión.</p>:null}
      {current?<div className="inventory-stack"><p className={`inventory-lifecycle inventory-lifecycle--${current.status.toLowerCase()}`}>Lote #{current.id} · {current.status}</p><dl className="inventory-evidence"><div><dt>Rendimiento esperado</dt><dd>{current.expected_yield}</dd></div><div><dt>Rendimiento real</dt><dd>{current.actual_yield}</dd></div><div><dt>Variación</dt><dd>{current.yield_variance}</dd></div><div><dt>Movimientos</dt><dd>{current.movements.length}</dd></div></dl><p className="inventory-state-note">Entrada: {current.inputs.map((row)=>`${itemName(itemRows,row.inventory_item_id)} ${row.source_quantity} ${row.source_uom}`).join(' · ')}<br/>Salida: {itemName(itemRows,current.output.inventory_item_id)} {current.output.source_quantity} {current.output.source_uom}</p><p>{current.cost_visible?(current.cost_evidence_status==='RESOLVED'?`Costo material ${current.material_cost} ${current.cost_currency_evidence} · unitario preparado ${current.prepared_unit_material_cost}`:'Costo no derivable; no se fabricó un cero.'):'Información monetaria protegida por permisos.'}</p><div className="inventory-actions">{current.status==='DRAFT'&&canManage?<button className="primary-button" disabled={action.isPending} onClick={()=>action.mutate('start')}>Iniciar lote</button>:null}{current.status==='IN_PROGRESS'&&canManage&&hasPermission('inventory.preparation.complete')?<button className="primary-button" disabled={action.isPending} onClick={()=>action.mutate('complete')}>Completar lote</button>:null}{['DRAFT','IN_PROGRESS'].includes(current.status)&&canManage?<button className="secondary-button" disabled={action.isPending} onClick={()=>action.mutate('cancel')}>Cancelar lote</button>:null}</div></div>:<p className="inventory-empty">Crea o selecciona un lote para revisar evidencia y resultado.</p>}
      {error?<p className="inventory-feedback inventory-feedback--error" role="alert">{errorMessage(error)}</p>:null}<div className="inventory-selection-list">{batches.data?.items.map((row)=><button type="button" className="inventory-selection" aria-pressed={current?.id===row.id} key={row.id} onClick={()=>setCurrent(row)}>Lote #{row.id} · {row.status}</button>)}</div>
    </section>
  </div>;
}
