"""Vendor-neutral Restaurant POS integration contract."""

from app.restaurant.integrations.pos.contracts import (
    CanonicalOrderStatus,
    ExternalCustomer,
    ExternalEntityStatus,
    ExternalLocation,
    ExternalOrder,
    ExternalOrderItem,
    ExternalOrderStatus,
    ExternalPrice,
    ExternalProduct,
    ExternalPromotion,
    LocationScopedPosRequestContext,
    PosRequestContext,
)
from app.restaurant.integrations.pos.errors import (
    PosErrorKind,
    PosIntegrationError,
    PosInvalidDataError,
    PosMappingError,
    PosNotFoundError,
    PosRejectedError,
    PosTemporaryFailureError,
    PosUncertainResultError,
    PosUnsupportedCapabilityError,
)
from app.restaurant.integrations.pos.ports import (
    CatalogPort,
    CustomerPort,
    LocationPort,
    OrderPort,
    OrderStatusPort,
    PricingPort,
    PromotionPort,
)

__all__ = [
    'CanonicalOrderStatus',
    'CatalogPort',
    'CustomerPort',
    'ExternalCustomer',
    'ExternalEntityStatus',
    'ExternalLocation',
    'ExternalOrder',
    'ExternalOrderItem',
    'ExternalOrderStatus',
    'ExternalPrice',
    'ExternalProduct',
    'ExternalPromotion',
    'LocationPort',
    'LocationScopedPosRequestContext',
    'OrderPort',
    'OrderStatusPort',
    'PosErrorKind',
    'PosIntegrationError',
    'PosInvalidDataError',
    'PosMappingError',
    'PosNotFoundError',
    'PosRejectedError',
    'PosRequestContext',
    'PosTemporaryFailureError',
    'PosUncertainResultError',
    'PosUnsupportedCapabilityError',
    'PricingPort',
    'PromotionPort',
]
