"""add atomic transfers and FIFO economic evidence

Revision ID: 0051_atomic_transfers_fifo
Revises: 0050_replenishment_lots_valuation
"""
from collections.abc import Sequence
from alembic import op
import sqlalchemy as sa

revision: str = '0051_atomic_transfers_fifo'
down_revision: str | None = '0050_replenishment_lots_valuation'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None
O={'mysql_engine':'InnoDB','mysql_charset':'utf8mb4','mysql_collate':'utf8mb4_unicode_ci'}
PERMISSIONS={
 'inventory.transfer.read':'Read inventory transfers.',
 'inventory.transfer.manage':'Create and execute inventory transfers.',
 'inventory.fifo.read':'Read FIFO layers and valuation evidence.',
}
def tables(): return sa.inspect(op.get_bind()).get_table_names()
def upgrade() -> None:
    try: op.drop_constraint('ck_stock_movements_type','stock_movements',type_='check')
    except Exception: pass
    try: op.drop_constraint('ck_stock_movements_sign','stock_movements',type_='check')
    except Exception: pass
    op.create_check_constraint('ck_stock_movements_type','stock_movements',"movement_type IN ('OPENING_BALANCE','MANUAL_IN','MANUAL_OUT','ADJUSTMENT','REVERSAL','CONSUMPTION','GOODS_RECEIPT','WASTE','PREPARATION_INPUT','PREPARATION_OUTPUT','TRANSFER_OUT','TRANSFER_IN')")
    op.create_check_constraint('ck_stock_movements_sign','stock_movements',"(movement_type IN ('OPENING_BALANCE','MANUAL_IN','GOODS_RECEIPT','PREPARATION_OUTPUT','TRANSFER_IN') AND quantity>0) OR (movement_type IN ('MANUAL_OUT','CONSUMPTION','WASTE','PREPARATION_INPUT','TRANSFER_OUT') AND quantity<0) OR (movement_type IN ('ADJUSTMENT','REVERSAL') AND quantity<>0)")
    if 'inventory_cost_layers' not in tables():
        op.create_table('inventory_cost_layers',
          sa.Column('id',sa.BigInteger(),primary_key=True,autoincrement=True),sa.Column('tenant_id',sa.BigInteger(),nullable=False),sa.Column('organization_id',sa.BigInteger(),nullable=False),sa.Column('location_id',sa.BigInteger(),nullable=False),sa.Column('warehouse_id',sa.BigInteger(),nullable=False),sa.Column('inventory_item_id',sa.BigInteger(),nullable=False),sa.Column('inventory_lot_id',sa.BigInteger()),sa.Column('source_inventory_lot_id',sa.BigInteger()),sa.Column('origin_type',sa.String(24),nullable=False),sa.Column('origin_id',sa.BigInteger(),nullable=False),sa.Column('origin_layer_id',sa.BigInteger()),sa.Column('origin_at',sa.DateTime(),nullable=False),sa.Column('original_quantity',sa.Numeric(19,6),nullable=False),sa.Column('remaining_quantity',sa.Numeric(19,6),nullable=False),sa.Column('unit_cost',sa.Numeric(31,12),nullable=False),sa.Column('currency',sa.String(3,collation='ascii_bin'),nullable=False),sa.Column('status',sa.String(16),server_default=sa.text("'ACTIVE'"),nullable=False),sa.Column('created_at',sa.DateTime(),server_default=sa.func.current_timestamp(),nullable=False),sa.Column('updated_at',sa.DateTime(),server_default=sa.func.current_timestamp(),nullable=False),
          sa.ForeignKeyConstraint(['warehouse_id','tenant_id','organization_id','location_id'],['warehouses.id','warehouses.tenant_id','warehouses.organization_id','warehouses.location_id'],name='fk_cost_layers_warehouse_scope',ondelete='RESTRICT'),sa.ForeignKeyConstraint(['inventory_item_id','tenant_id','organization_id','location_id'],['inventory_items.id','inventory_items.tenant_id','inventory_items.organization_id','inventory_items.location_id'],name='fk_cost_layers_item_scope',ondelete='RESTRICT'),sa.ForeignKeyConstraint(['inventory_lot_id','tenant_id','organization_id','location_id','warehouse_id','inventory_item_id'],['inventory_lots.id','inventory_lots.tenant_id','inventory_lots.organization_id','inventory_lots.location_id','inventory_lots.warehouse_id','inventory_lots.inventory_item_id'],name='fk_cost_layers_lot_scope',ondelete='RESTRICT'),sa.ForeignKeyConstraint(['source_inventory_lot_id'],['inventory_lots.id'],name='fk_inventory_cost_layers_source_inventory_lot_id_inventory_lots',ondelete='RESTRICT'),sa.UniqueConstraint('id','tenant_id','organization_id','location_id','warehouse_id','inventory_item_id',name='uq_cost_layers_scope'),sa.UniqueConstraint('origin_type','origin_id','origin_layer_id',name='uq_cost_layers_origin'),sa.CheckConstraint("origin_type IN ('GOODS_RECEIPT','PREPARATION_OUTPUT','TRANSFER')",name='ck_cost_layers_origin'),sa.CheckConstraint("status IN ('ACTIVE','DEPLETED')",name='ck_cost_layers_status'),sa.CheckConstraint('original_quantity > 0 AND remaining_quantity >= 0 AND remaining_quantity <= original_quantity AND unit_cost >= 0',name='ck_cost_layers_values'),sa.CheckConstraint("currency REGEXP '^[A-Z][A-Z][A-Z]$'",name='ck_cost_layers_currency'),**O)
        op.create_index('ix_cost_layers_fifo','inventory_cost_layers',['tenant_id','warehouse_id','inventory_item_id','status','origin_at','id'])
    if 'inventory_transfers' not in tables():
        op.create_table('inventory_transfers',sa.Column('id',sa.BigInteger(),primary_key=True,autoincrement=True),sa.Column('tenant_id',sa.BigInteger(),nullable=False),sa.Column('organization_id',sa.BigInteger(),nullable=False),sa.Column('location_id',sa.BigInteger(),nullable=False),sa.Column('source_warehouse_id',sa.BigInteger(),nullable=False),sa.Column('destination_warehouse_id',sa.BigInteger(),nullable=False),sa.Column('status',sa.String(16),server_default=sa.text("'DRAFT'"),nullable=False),sa.Column('reference',sa.String(200)),sa.Column('version',sa.BigInteger(),server_default=sa.text('1'),nullable=False),sa.Column('created_by_actor_id',sa.BigInteger(),nullable=False),sa.Column('submitted_at',sa.DateTime()),sa.Column('shipped_at',sa.DateTime()),sa.Column('received_at',sa.DateTime()),sa.Column('cancelled_at',sa.DateTime()),sa.Column('last_command_key',sa.String(128,collation='ascii_bin')),sa.Column('last_command_action',sa.String(16,collation='ascii_bin')),sa.Column('created_at',sa.DateTime(),server_default=sa.func.current_timestamp(),nullable=False),sa.Column('updated_at',sa.DateTime(),server_default=sa.func.current_timestamp(),nullable=False),sa.ForeignKeyConstraint(['source_warehouse_id','tenant_id','organization_id','location_id'],['warehouses.id','warehouses.tenant_id','warehouses.organization_id','warehouses.location_id'],name='fk_transfers_source_scope',ondelete='RESTRICT'),sa.ForeignKeyConstraint(['destination_warehouse_id','tenant_id','organization_id','location_id'],['warehouses.id','warehouses.tenant_id','warehouses.organization_id','warehouses.location_id'],name='fk_transfers_destination_scope',ondelete='RESTRICT'),sa.UniqueConstraint('id','tenant_id','organization_id','location_id',name='uq_transfers_scope'),sa.CheckConstraint("status IN ('DRAFT','SUBMITTED','IN_TRANSIT','RECEIVED','CANCELLED')",name='ck_transfers_status'),sa.CheckConstraint('source_warehouse_id <> destination_warehouse_id AND version >= 1',name='ck_transfers_values'),**O)
    if 'inventory_transfer_lines' not in tables():
        op.create_table('inventory_transfer_lines',sa.Column('id',sa.BigInteger(),primary_key=True,autoincrement=True),sa.Column('tenant_id',sa.BigInteger(),nullable=False),sa.Column('organization_id',sa.BigInteger(),nullable=False),sa.Column('location_id',sa.BigInteger(),nullable=False),sa.Column('transfer_id',sa.BigInteger(),nullable=False),sa.Column('inventory_item_id',sa.BigInteger(),nullable=False),sa.Column('line_number',sa.Integer(),nullable=False),sa.Column('sent_quantity',sa.Numeric(19,6),nullable=False),sa.Column('received_quantity',sa.Numeric(19,6),server_default=sa.text('0'),nullable=False),sa.Column('source_movement_id',sa.BigInteger()),sa.Column('created_at',sa.DateTime(),server_default=sa.func.current_timestamp(),nullable=False),sa.ForeignKeyConstraint(['transfer_id','tenant_id','organization_id','location_id'],['inventory_transfers.id','inventory_transfers.tenant_id','inventory_transfers.organization_id','inventory_transfers.location_id'],name='fk_transfer_lines_transfer_scope',ondelete='RESTRICT'),sa.ForeignKeyConstraint(['inventory_item_id','tenant_id','organization_id','location_id'],['inventory_items.id','inventory_items.tenant_id','inventory_items.organization_id','inventory_items.location_id'],name='fk_transfer_lines_item_scope',ondelete='RESTRICT'),sa.ForeignKeyConstraint(['source_movement_id'],['stock_movements.id'],name='fk_inventory_transfer_lines_source_movement_id_stock_movements',ondelete='RESTRICT'),sa.UniqueConstraint('transfer_id','line_number',name='uq_transfer_lines_number'),sa.UniqueConstraint('transfer_id','inventory_item_id',name='uq_transfer_lines_item'),sa.CheckConstraint('line_number >= 1 AND sent_quantity > 0 AND received_quantity >= 0 AND received_quantity <= sent_quantity',name='ck_transfer_lines_values'),**O)
    if 'inventory_movement_cost_allocations' not in tables():
        op.create_table('inventory_movement_cost_allocations',sa.Column('id',sa.BigInteger(),primary_key=True,autoincrement=True),sa.Column('tenant_id',sa.BigInteger(),nullable=False),sa.Column('stock_movement_id',sa.BigInteger(),nullable=False),sa.Column('cost_layer_id',sa.BigInteger(),nullable=False),sa.Column('quantity',sa.Numeric(19,6),nullable=False),sa.Column('unit_cost',sa.Numeric(31,12),nullable=False),sa.Column('extended_cost',sa.Numeric(31,12),nullable=False),sa.Column('currency',sa.String(3,collation='ascii_bin'),nullable=False),sa.Column('allocation_order',sa.Integer(),nullable=False),sa.Column('created_at',sa.DateTime(),server_default=sa.func.current_timestamp(),nullable=False),sa.ForeignKeyConstraint(['cost_layer_id'],['inventory_cost_layers.id'],name='fk_fifo_allocations_layer',ondelete='RESTRICT'),sa.ForeignKeyConstraint(['stock_movement_id'],['stock_movements.id'],name='fk_fifo_allocations_movement',ondelete='RESTRICT'),sa.UniqueConstraint('stock_movement_id','allocation_order',name='uq_fifo_allocations_order'),sa.UniqueConstraint('stock_movement_id','cost_layer_id',name='uq_fifo_allocations_layer'),sa.CheckConstraint('quantity > 0 AND unit_cost >= 0 AND extended_cost >= 0 AND allocation_order >= 1',name='ck_fifo_allocations_values'),**O)
    if 'inventory_transfer_receipts' not in tables():
        op.create_table('inventory_transfer_receipts',sa.Column('id',sa.BigInteger(),primary_key=True,autoincrement=True),sa.Column('tenant_id',sa.BigInteger(),nullable=False),sa.Column('transfer_line_id',sa.BigInteger(),nullable=False),sa.Column('receipt_sequence',sa.Integer(),nullable=False),sa.Column('source_layer_id',sa.BigInteger(),nullable=False),sa.Column('destination_layer_id',sa.BigInteger(),nullable=False),sa.Column('destination_movement_id',sa.BigInteger(),nullable=False),sa.Column('quantity',sa.Numeric(19,6),nullable=False),sa.Column('unit_cost',sa.Numeric(31,12),nullable=False),sa.Column('extended_cost',sa.Numeric(31,12),nullable=False),sa.Column('currency',sa.String(3,collation='ascii_bin'),nullable=False),sa.Column('created_at',sa.DateTime(),server_default=sa.func.current_timestamp(),nullable=False),sa.ForeignKeyConstraint(['transfer_line_id'],['inventory_transfer_lines.id'],name='fk_transfer_receipts_line',ondelete='RESTRICT'),sa.ForeignKeyConstraint(['source_layer_id'],['inventory_cost_layers.id'],name='fk_transfer_receipts_source_layer',ondelete='RESTRICT'),sa.ForeignKeyConstraint(['destination_layer_id'],['inventory_cost_layers.id'],name='fk_transfer_receipts_destination_layer',ondelete='RESTRICT'),sa.ForeignKeyConstraint(['destination_movement_id'],['stock_movements.id'],name='fk_transfer_receipts_movement',ondelete='RESTRICT'),sa.UniqueConstraint('transfer_line_id','receipt_sequence','source_layer_id',name='uq_transfer_receipts_evidence'),sa.CheckConstraint('receipt_sequence >= 1 AND quantity > 0 AND unit_cost >= 0 AND extended_cost >= 0',name='ck_transfer_receipts_values'),**O)
    cols={x['name'] for x in sa.inspect(op.get_bind()).get_columns('inventory_valuation_snapshots')}
    if 'layer_cursor' not in cols: op.add_column('inventory_valuation_snapshots',sa.Column('layer_cursor',sa.BigInteger(),server_default=sa.text('0'),nullable=False))
    movement_cols={x['name'] for x in sa.inspect(op.get_bind()).get_columns('stock_movements')}
    if 'fifo_evidence_status' not in movement_cols: op.add_column('stock_movements',sa.Column('fifo_evidence_status',sa.String(24),server_default=sa.text("'FIFO_NON_DERIVABLE'"),nullable=False))
    if 'fifo_extended_cost' not in movement_cols: op.add_column('stock_movements',sa.Column('fifo_extended_cost',sa.Numeric(31,12)))
    if 'fifo_currency' not in movement_cols: op.add_column('stock_movements',sa.Column('fifo_currency',sa.String(3,collation='ascii_bin')))
    try: op.drop_constraint('ck_inventory_valuation_snapshots_authority','inventory_valuation_snapshots',type_='check')
    except Exception: pass
    try: op.drop_constraint('ck_inventory_valuation_snapshots_values','inventory_valuation_snapshots',type_='check')
    except Exception: pass
    op.create_check_constraint('ck_inventory_valuation_snapshots_authority','inventory_valuation_snapshots',"status='FINALIZED' AND valuation_method IN ('STANDARD_COST','FIFO')")
    op.create_check_constraint('ck_inventory_valuation_snapshots_values','inventory_valuation_snapshots','movement_cursor >= 0 AND layer_cursor >= 0 AND non_derivable_line_count >= 0')
    if 'inventory_valuation_snapshot_fifo_layers' not in tables():
        op.create_table('inventory_valuation_snapshot_fifo_layers',sa.Column('id',sa.BigInteger(),primary_key=True,autoincrement=True),sa.Column('tenant_id',sa.BigInteger(),nullable=False),sa.Column('snapshot_id',sa.BigInteger(),nullable=False),sa.Column('inventory_item_id',sa.BigInteger(),nullable=False),sa.Column('cost_layer_id',sa.BigInteger(),nullable=False),sa.Column('quantity_as_of',sa.Numeric(19,6),nullable=False),sa.Column('unit_cost_evidence',sa.Numeric(31,12)),sa.Column('cost_currency_evidence',sa.String(3,collation='ascii_bin')),sa.Column('line_value',sa.Numeric(31,12)),sa.Column('evidence_status',sa.String(24),nullable=False),sa.Column('created_at',sa.DateTime(),server_default=sa.func.current_timestamp(),nullable=False),sa.ForeignKeyConstraint(['snapshot_id'],['inventory_valuation_snapshots.id'],name='fk_fifo_snapshot_layers_snapshot',ondelete='RESTRICT'),sa.ForeignKeyConstraint(['cost_layer_id'],['inventory_cost_layers.id'],name='fk_fifo_snapshot_layers_layer',ondelete='RESTRICT'),sa.UniqueConstraint('snapshot_id','cost_layer_id',name='uq_fifo_snapshot_layers_layer'),sa.CheckConstraint("evidence_status IN ('RESOLVED','FIFO_NON_DERIVABLE','CURRENCY_MISMATCH')",name='ck_fifo_snapshot_layers_status'),sa.CheckConstraint('quantity_as_of >= 0',name='ck_fifo_snapshot_layers_quantity'),**O)
    c=op.get_bind()
    for code,desc in PERMISSIONS.items():
        c.execute(sa.text('INSERT INTO permissions (code,description) SELECT :c,:d WHERE NOT EXISTS (SELECT 1 FROM permissions WHERE code=:c)'),{'c':code,'d':desc})
        c.execute(sa.text("INSERT INTO role_permissions (role_id,permission_id) SELECT r.id,p.id FROM roles r JOIN permissions p ON p.code=:c WHERE r.name='TENANT_ADMIN' AND r.status='ACTIVE' AND NOT EXISTS (SELECT 1 FROM role_permissions x WHERE x.role_id=r.id AND x.permission_id=p.id)"),{'c':code})
def downgrade() -> None:
    c=op.get_bind()
    for t in ('inventory_transfer_receipts','inventory_movement_cost_allocations','inventory_transfer_lines','inventory_transfers','inventory_valuation_snapshot_fifo_layers','inventory_cost_layers'):
        if t in tables() and c.execute(sa.text(f'SELECT COUNT(*) FROM {t}')).scalar_one(): raise RuntimeError(f'Cannot downgrade 0051 while {t} contains evidence')
    for t in ('inventory_transfer_receipts','inventory_movement_cost_allocations','inventory_transfer_lines','inventory_transfers','inventory_valuation_snapshot_fifo_layers','inventory_cost_layers'):
        if t in tables(): op.drop_table(t)
    op.drop_constraint('ck_inventory_valuation_snapshots_authority','inventory_valuation_snapshots',type_='check'); op.drop_constraint('ck_inventory_valuation_snapshots_values','inventory_valuation_snapshots',type_='check')
    op.create_check_constraint('ck_inventory_valuation_snapshots_authority','inventory_valuation_snapshots',"status='FINALIZED' AND valuation_method='STANDARD_COST'"); op.create_check_constraint('ck_inventory_valuation_snapshots_values','inventory_valuation_snapshots','movement_cursor >= 0 AND non_derivable_line_count >= 0'); op.drop_column('inventory_valuation_snapshots','layer_cursor'); op.drop_column('stock_movements','fifo_currency'); op.drop_column('stock_movements','fifo_extended_cost'); op.drop_column('stock_movements','fifo_evidence_status')
    op.drop_constraint('ck_stock_movements_type','stock_movements',type_='check'); op.drop_constraint('ck_stock_movements_sign','stock_movements',type_='check')
    op.create_check_constraint('ck_stock_movements_type','stock_movements',"movement_type IN ('OPENING_BALANCE','MANUAL_IN','MANUAL_OUT','ADJUSTMENT','REVERSAL','CONSUMPTION','GOODS_RECEIPT','WASTE','PREPARATION_INPUT','PREPARATION_OUTPUT')")
    op.create_check_constraint('ck_stock_movements_sign','stock_movements',"(movement_type IN ('OPENING_BALANCE','MANUAL_IN','GOODS_RECEIPT','PREPARATION_OUTPUT') AND quantity>0) OR (movement_type IN ('MANUAL_OUT','CONSUMPTION','WASTE','PREPARATION_INPUT') AND quantity<0) OR (movement_type IN ('ADJUSTMENT','REVERSAL') AND quantity<>0)")
